/**
 * Modules in this bundle
 * @license
 *
 * hiraku:
 *   license: MIT (http://opensource.org/licenses/MIT)
 *   author: appleple
 *   version: 1.0.10
 *
 * This header is generated by licensify (https://github.com/twada/licensify)
 */
(function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}return e})()({1:[function(require,module,exports){
'use strict';

var hiraku = require('../index');

var applyJQuery = function applyJQuery(jQuery) {
  jQuery.fn.hiraku = function (settings) {
    if (typeof settings === 'strings') {} else {
      new hiraku(this, settings);
    }
    return this;
  };
};

if (typeof define === 'function' && define.amd) {
  define(['jquery'], applyJQuery);
} else {
  var jq = window.jQuery ? window.jQuery : window.$;
  if (typeof jq !== 'undefined') {
    applyJQuery(jq);
  }
}

module.exports = applyJQuery;

},{"../index":3}],2:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _lib = require('../lib');

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var defaults = {
  direction: 'right',
  breakpoint: -1,
  btn: '.js-hiraku-offcanvas-btn',
  btnLabel: 'Menu',
  closeLabel: 'Close',
  // fixedHeader: '.js-hiraku-fixed-header',
  focusableElements: 'a[href], area[href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), button:not([disabled]), iframe, object, embed, *[tabindex], *[contenteditable]'
};

var Hiraku = function () {
  function Hiraku(selector, opt) {
    var _this = this;

    _classCallCheck(this, Hiraku);

    this.body = document.querySelector('body');
    this.opt = Object.assign({}, defaults, opt);
    this.side = document.querySelector(selector);
    this.btn = document.querySelector(opt.btn);
    this.fixed = document.querySelector(opt.fixedHeader);
    this.windowWidth = (0, _lib.getWindowWidth)();
    this.id = (0, _lib.getUniqId)();
    window.addEventListener('resize', function () {
      if ('requestAnimationFrame' in window) {
        cancelAnimationFrame(_this.animationFrameId);
        _this.animationFrameId = requestAnimationFrame(resizeHandler);
      } else {
        _this.resizeHandler();
      }
    });
    this._setHirakuSideMenu(this.side, this.id);
    this._setHirakuBtn(this.btn, this.id);
    this._setHirakuBody(this.body);
    if (this.fixed) {
      (0, _lib.addClass)(this.fixed, 'js-hiraku-header-fixed');
    }
  }

  _createClass(Hiraku, [{
    key: '_setHirakuSideMenu',
    value: function _setHirakuSideMenu(side, id) {
      var _this2 = this;

      var _opt = this.opt,
          closeLabel = _opt.closeLabel,
          direction = _opt.direction;

      var parent = side.parentElement;
      if (!(0, _lib.hasClass)(parent, 'js-hiraku-offcanvas')) {
        var div = document.createElement('div');
        (0, _lib.addClass)(div, 'js-hiraku-offcanvas');
        div.appendChild(side);
        parent = side.parentElement;
      }
      if (direction === 'right') {
        (0, _lib.addClass)(side, 'js-hiraku-offcanvas-sidebar-right');
      } else {
        (0, _lib.addClass)(side, 'js-hiraku-offcanvas-sidebar-left');
      }
      parent.setAttribute('aria-hidden', true);
      parent.setAttribute('aria-labelledby', 'hiraku-offcanvas-btn-' + id);
      parent.setAttribute('id', id);
      parent.setAttribute('aria-label', closeLabel);
      this.parent = parent;
      parent.addEventListener('click', function (e) {
        _this2.offcanvasClickHandler(e);
      });
      parent.addEventListener('touchstart', function (e) {
        _this2.offcanvasClickHandler(e);
      });
      parent.addEventListener('keyup', function (e) {
        _this2.offcanvasClickHandler(e);
      });
    }
  }, {
    key: '_setHirakuBtn',
    value: function _setHirakuBtn(btn, id) {
      var _this3 = this;

      var btnLabel = this.opt.btnLabel;

      (0, _lib.addClass)(btn, 'js-hiraku-offcanvas-btn');
      btn.setAttribute('aria-expanded', false);
      btn.setAttribute('aria-label', btnLabel);
      btn.setAttribute('aria-controls', id);
      btn.setAttribute('id', 'hiraku-offcanvas-btn-' + id);
      btn.addEventListener('click', function (e) {
        _this3.clickHandler(e);
      });
    }
  }, {
    key: '_setHirakuBody',
    value: function _setHirakuBody(body) {
      var direction = this.opt.direction;

      (0, _lib.addClass)(body, 'js-hiraku-offcanvas-body');
    }
  }, {
    key: 'clickHandler',
    value: function clickHandler(e) {
      var side = this.side,
          btn = this.btn,
          fixed = this.fixed,
          parent = this.parent,
          body = this.body;
      var _opt2 = this.opt,
          position = _opt2.position,
          focusableElements = _opt2.focusableElements;

      var elements = side.querySelectorAll(focusableElements);
      var first = elements[0];
      var last = elements[elements.length - 1];
      var lastFocus = function lastFocus(e) {
        if (e.which === 9 && e.shiftKey) {
          last.focus();
        }
      };
      var firstFocus = function firstFocus(e) {
        if (e.which === 9 && !e.shiftKey) {
          first.focus();
        }
      };

      first.removeEventListener('keydown', lastFocus);
      first.addEventListener('keydown', lastFocus);
      last.removeEventListener('keydown', firstFocus);
      last.addEventListener('keydown', firstFocus);
      btn.setAttribute('aria-expanded', true);
      (0, _lib.addClass)(btn, 'js-hiraku-offcanvas-btn-active');
      parent.setAttribute('aria-hidden', false);
      if (position === 'right') {
        (0, _lib.addClass)(body, 'js-hiraku-offcanvas-body-right');
      } else {
        (0, _lib.addClass)(body, 'js-hiraku-offcanvas-body-left');
      }
      first.focus();
    }
  }, {
    key: 'offcanvasClickHandler',
    value: function offcanvasClickHandler(e) {
      var parent = this.parent,
          body = this.body;
      var position = this.opt.position;

      if (e.type === 'keyup' && e.keyCode !== 27) {
        return;
      }
      if (e.target !== parent) {
        return;
      }
      if (position === 'right') {
        removeClass(body, 'js-hiraku-offcanvas-body-right');
      } else {
        removeClass(body, 'js-hiraku-offcanvas-body-left');
      }
    }
  }, {
    key: 'resizeHandler',
    value: function resizeHandler() {
      var windowWidth = (0, _lib.getWindowWidth)();
      var breakpoint = this.opt.breakpoint;

      var ele = this.ele;
      if (windowWidth === this.windowWidth) {
        return;
      }
      this.windowWidth = windowWidth;
      if ((0, _lib.hasClass)(ele, 'js-hiraku-offcanvas-open') && (breakpoint === 1 || breakpoint >= windowWidth)) {
        return;
      }
      if (breakpoint === -1 || breakpoint >= windowWidth) {
        (0, _lib.addClass)(ele, 'js-hiraku-offcanvas-active');
        ele.setAttribute('aria-hidden', true);
      } else {
        removeClass(ele, 'js-hiraku-offcanvas-active');
        ele.setAttribute('aria-hidden', false);
        ele.click();
      }
    }
  }]);

  return Hiraku;
}();

exports.default = Hiraku;
module.exports = exports['default'];

},{"../lib":4}],3:[function(require,module,exports){
'use strict';

module.exports = require('./core/');

},{"./core/":2}],4:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var getUniqId = exports.getUniqId = function getUniqId() {
  return (Date.now().toString(36) + Math.random().toString(36).substr(2, 5)).toUpperCase();
};

var getWindowWidth = exports.getWindowWidth = function getWindowWidth() {
  if (document && document.documentElement) {
    return document.documentElement.clientWidth;
  } else if (window && window.innerWidth) {
    return window.innerWidth;
  }
  return 0;
};

var hasClass = exports.hasClass = function hasClass(el, className) {
  if (el.classList) {
    el.classList.contains(className);
  } else {
    new RegExp('(^| )' + className + '( |$)', 'gi').test(el.className);
  }
};

var addClass = exports.addClass = function addClass(element, className) {
  if (element.classList) {
    element.classList.add(className);
  } else {
    element.className += ' ' + className;
  }
};

},{}]},{},[1]);
